# Generated by Django 6.0.7 on 2026-08-07 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='productSize',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='products.productsize'),
        ),
    ]
