# Generated by Django 6.0.7 on 2026-08-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_image_url1_alter_orders_productsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolorimage',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
