# Generated by Django 6.0.7 on 2026-08-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productcolorimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivrisonPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('willya', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='commend',
            name='commune',
        ),
    ]
