# Generated by Django 6.0.7 on 2026-08-08 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_livrisonprice_remove_commend_commune'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commend',
            old_name='wilaya',
            new_name='willya',
        ),
        migrations.AddField(
            model_name='commend',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
