# Generated by Django 6.0.7 on 2026-08-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_compte'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='eqSize',
            field=models.CharField(blank=True, choices=[('34', 'XS'), ('36', 'S'), ('38', 'M'), ('40', 'L'), ('42', 'XL'), ('44', 'XXL'), ('46', 'XXXL'), ('48', 'XXXXL'), ('50', 'XXXXXL')], null=True),
        ),
        migrations.AlterField(
            model_name='productcolorimage',
            name='color',
            field=models.CharField(blank=True, choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('BLACK', 'Black'), ('WHITE', 'White'), ('YELLOW', 'Yellow'), ('PINK', 'Pink'), ('PURPLE', 'Purple'), ('ORANGE', 'Orange'), ('GRAY', 'Gray'), ('BROWN', 'Brown'), ('BEIGE', 'Beige'), ('NAVY', 'Navy'), ('BURGUNDY', 'Burgundy'), ('TEAL', 'Teal'), ('CREAM', 'Cream'), ('GOLD', 'Gold'), ('SILVER', 'Silver'), ('KHAKI', 'Khaki'), ('OLIVE', 'Olive')], null=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large'), ('XXXL', 'Triple Extra Large'), ('XXXXL', '4X Large'), ('XXXXXL', '5X Large')], null=True),
        ),
    ]
