# Generated by Django 6.0.7 on 2026-08-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productsize_eqsize_alter_productcolorimage_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commend',
            name='baladiya',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='livrisonprice',
            name='baladiya',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='livrisonprice',
            name='willya',
            field=models.CharField(max_length=100),
        ),
    ]
