# Generated by Django 6.0.7 on 2026-08-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_commend_baladiya_livrisonprice_baladiya_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commend',
            name='is_birou',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livrisonprice',
            name='is_birou',
            field=models.BooleanField(default=False),
        ),
    ]
